### ISSUE TITLE
KeyError: 'смена_темы'

### ISSUE THREAD

**Issue by GraphGrailAi** [Koziev/chatbot#21]
На реплику "ну хватит об этом" ошибка:

```
B:> Спасибо за хорошую оценку
H:> ну хватит об этом
2020-03-19 17:51:39 INFO     SimpleAnsweringMachine  - push_phrase interlocutor="test" phrase="ну хватит об этом"
2020-03-19 17:51:39 DEBUG    SimpleAnsweringMachine  - intent="смена_темы"
2020-03-19 17:51:39 DEBUG    SimpleAnsweringMachine  - Processing as assertion: "ну хватит об этом"
2020-03-19 17:51:41 DEBUG    root  - ScriptingRuleIf "реакция на предложение сменить тему разговора"
Traceback (most recent call last):
  File "../ruchatbot/frontend/console_chatbot.py", line 160, in <module>
    main()
  File "../ruchatbot/frontend/console_chatbot.py", line 156, in main
    bot.push_phrase(user_id, question)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/bot_personality.py", line 63, in push_phrase
    force_question_answering=self.force_question_answering)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/simple_answering_machine.py", line 880, in push_phrase
    interpreted_phrase)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/simple_answering_machine.py", line 658, in apply_insteadof_rule
    rule_result = rule.execute(bot, session, interlocutor, interpreted_phrase, self)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/scripting_rule.py", line 75, in execute
    condition_check, answering_engine.text_utils)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/actors.py", line 325, in do_action
    bot.run_form(self, session, interlocutor, interpreted_phrase)
  File "/home/joo/Docs/LocalRepository/chatbot-0.0.2.8-alpha/ruchatbot/bot/bot_personality.py", line 96, in run_form
    raise KeyError(form_actor.form_name)
KeyError: 'смена_темы'

```

**Comment by Koziev** [comment]
>На реплику "ну хватит об этом" ошибка:

Большое спасибо за замечание, буду разбираться!

**Comment by Koziev** [comment]
Исправил в последнем релизе.
