### ISSUE TITLE
При запуске возникает еще ошибка

### ISSUE THREAD

**Issue by SerzhNS** [Koziev/chatbot#3]
./console_bot.sh
Using TensorFlow backend.
[LightGBM] [Fatal] Tree model should contain num_cat field
Traceback (most recent call last):
  File "../PyModels/console_chatbot.py", line 40, in <module>
    bot.load_models(models_folder, w2v_folder)
  File "/home/ssn/WORK/Koziev/chatbot-master/PyModels/bot/simple_answering_machine.py", line 74, in load_models
    self.relevancy_detector.load(models_folder)
  File "/home/ssn/WORK/Koziev/chatbot-master/PyModels/bot/lgb_relevancy_detector.py", line 29, in load
    self.lgb_relevancy = lightgbm.Booster(model_file=os.path.join(models_folder, os.path.basename(model_config['model_filename'])))
  File "/home/ssn/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1499, in __init__
    ctypes.byref(self.handle)))
  File "/home/ssn/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 44, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Tree model should contain num_cat field

**Comment by SerzhNS** [comment]
Что-то некорректно с заданием названия файла модели - 'model_filename'.

**Comment by SerzhNS** [comment]
Устранил эту ошибку путем перетренировки lgb_relevancy.model под требования последней версии LightGBM.
Но возникает новая ошибка
Traceback (most recent call last):
  File "../PyModels/console_chatbot.py", line 40, in <module>
    bot.load_models(models_folder, w2v_folder)
  File "/home/ssn/WORK/Koziev/chatbot-master/PyModels/bot/simple_answering_machine.py", line 97, in load_models
    self.person_changer.load(models_folder)
  File "/home/ssn/WORK/Koziev/chatbot-master/PyModels/bot/nn_person_change.py", line 25, in load
    with open(os.path.join(models_folder, 'person_change_dictionary.pickle'), 'r') as f:
IOError: [Errno 2] No such file or directory: '../tmp/person_change_dictionary.pickle'.
??

**Comment by SerzhNS** [comment]
Отсутствует  # Упрощенная модель для работы с грамматическим лицом  'person_change_dictionary.pickle'.
Прошу добавить.

**Comment by Koziev** [comment]
>
> Отсутствует # Упрощенная модель для работы с грамматическим лицом
> 'person_change_dictionary.pickle'.
> Прошу добавить.
>
Сделано.

Добавил в код бота еще логирование в файл, в частности при загрузке модели
релевантности в логе (по дефолту будет ../tmp/console_chatbot.log) появится
что-то вроде:

2018-09-25 14:04:32,756 | LGB_RelevancyDetector |  INFO: Loading LightGBM
model from ../tmp/lgb_relevancy.model

Это чтобы контролировать, откуда грузятся модели.

**Comment by SerzhNS** [comment]
Спасибо. Сейчас попробую.

Еще не хватает файла /data/pqa_yes_no.dat.
Прошу добавить.

**Comment by Koziev** [comment]
>
> Еще не хватает файла /data/pqa_yes_no.dat.
>
Добавил в реп файлы pqa_yes_no.dat и pqa_all.dat (примерно по трети от
полных датасетов).

**Comment by SerzhNS** [comment]
Илья, спасибо. Дальше попробую разобраться сам. Информации, размещенной Вами, более, чем достаточно. Если уж будет полный затык, то обращусь.  Благодарю. С уважением
