### ISSUE TITLE
что должно лежать в директории w2c_folder?

### ISSUE THREAD

**Issue by iru-dev** [Koziev/chatbot#43]
`$ ./console_bot.sh        
Traceback (most recent call last):
  File "/home/iru/git/chatbot/scripts/../ruchatbot/frontend/console_chatbot.py", line 97, in <module>
    bot = create_chatbot(profile_path, models_folder, w2v_folder, data_folder, args.debugging, chitchat_config=rugpt_chitchat_config)
  File "/home/iru/git/chatbot/ruchatbot/frontend/bot_creator.py", line 51, in create_chatbot
    text_utils.load_embeddings(w2v_dir=w2v_folder, wc2v_dir=None)
  File "/home/iru/git/chatbot/ruchatbot/bot/text_utils.py", line 87, in load_embeddings
    self.word_embeddings.load_w2v_model(p)
  File "/home/iru/git/chatbot/ruchatbot/bot/word_embeddings.py", line 51, in load_w2v_model
    w2v = gensim.models.KeyedVectors.load(w2v_path, mmap='r')
  File "/home/iru/.local/lib/python3.9/site-packages/gensim/utils.py", line 485, in load
    obj = unpickle(fname)
  File "/home/iru/.local/lib/python3.9/site-packages/gensim/utils.py", line 1459, in unpickle
    with open(fname, 'rb') as f:
  File "/home/iru/.local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 188, in open
    fobj = _shortcut_open(
  File "/home/iru/.local/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 361, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '../tmp/w2v.kv'`

**Comment by Koziev** [comment]
Привет,
>[Errno 2] No such file or directory: '../tmp/w2v.kv'

Судя по этой ошибке, код не смог загрузить файл с word2vec эмбеддингами слова. Проще всего его (и остальные файлы моделей) достать из докер-контейнера бота, он есть на dockerhub'е под именем inkoziev/chatbot.

**Comment by iru-dev** [comment]
Докер не выкачивает все слои и сбрасывается. может есть возможность в Telegram пообщаться?

**Comment by Koziev** [comment]
> может есть возможность в Telegram пообщаться?

Лучше почтой, которая у меня в профиле указана. На живое общение в телеграмме практически нет времени :(

**Comment by iru-dev** [comment]
Данному проекту явно не хватает документации по развертыванию и обучению
моделей. Из коробки и docker образ по итогу не рабочие

вт, 16 нояб. 2021 г. в 15:46, Илья Козиев ***@***.***>:
