### ISSUE TITLE
Где взять w2v.kv

### ISSUE THREAD

**Issue by Fatonndev** [Koziev/chatbot#50]
Ошибка
FileNotFoundError: [Errno 2] No such file or directory: '../tmp\\w2v.kv'

Пытался сам его собрать, честно, ошибки, ошибки, еще раз ошибки, качал докер, пытался запустить, получал Illegal instruction.
Ковырял файлы, искал, нашел всё кроме этого файла.

Можете скинуть плиз?

**Comment by Koziev** [comment]
Привет,

[архив w2v модели](https://drive.google.com/file/d/10uVWlWN-iHKY0j34WFbcbpc8rEhbF2qJ/view?usp=sharing)

**Comment by Fatonndev** [comment]
![изображение](https://user-images.githubusercontent.com/56699208/170867539-87048763-3d29-4a1f-bc8c-77ec32cf125f.png)
Доступ закрыт

**Comment by Koziev** [comment]
>Доступ закрыт

Да, забыл - попробуйте сейчас, расшарил архив.

**Comment by Fatonndev** [comment]
Окей, спасибо за поддержку, только вот опять беды, не может определить пол ассистента как я понял.
```
...
2022-05-29 16:17:16 DEBUG    root  - Bot loading: profile="../data\profile_1.json"
2022-05-29 16:17:16 INFO     WordEmbeddings  - Loading word2vector from "../tmp\w2v.kv"
2022-05-29 16:17:16 INFO     gensim.utils  - loading KeyedVectors object from ../tmp\w2v.kv
2022-05-29 16:17:16 DEBUG    smart_open.smart_open_lib  - {'uri': '../tmp\\w2v.kv', 'mode': 'rb', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}
2022-05-29 16:17:17 INFO     gensim.utils  - loading vectors from ../tmp\w2v.kv.vectors.npy with mmap=r
2022-05-29 16:17:17 INFO     gensim.utils  - setting ignored attribute vectors_norm to None
2022-05-29 16:17:19 DEBUG    gensim.utils  - starting a new internal lifecycle event log for KeyedVectors
2022-05-29 16:17:19 INFO     gensim.utils  - KeyedVectors lifecycle event {'fname': '../tmp\\w2v.kv', 'datetime': '2022-05-29T16:17:19.874042', 'gensim': '4.2.0', 'python': '3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]', 'platform': 'Windows-10-10.0.18363-SP0', 'event': 'loaded'}
2022-05-29 16:17:36 DEBUG    root  - Loading rules from "../data/profile_rules_1.yaml"...
Traceback (most recent call last):
  File "G:\chatbot\ruchatbot\frontend\telegram_bot.py", line 125, in <module>
    chatbot = create_chatbot(profile_path, models_folder, w2v_folder, data_folder, True, bot_id=bot_id,
  File "C:\Users\Fatonn\AppData\Local\Programs\Python\Python39\lib\site-packages\ruchatbot\frontend\bot_creator.py", line 60, in create_chatbot
    scripting.load_rules(profile.rules_path, profile.smalltalk_generative_rules, profile.constants, text_utils)
  File "C:\Users\Fatonn\AppData\Local\Programs\Python\Python39\lib\site-packages\ruchatbot\bot\bot_scripting.py", line 187, in load_rules
    self.greetings.append(replace_constant(s, constants, text_utils))
  File "C:\Users\Fatonn\AppData\Local\Programs\Python\Python39\lib\site-packages\ruchatbot\utils\constant_replacer.py", line 27, in replace_constant
    word = text_utils.apply_word_function(func, constants, words)
  File "C:\Users\Fatonn\AppData\Local\Programs\Python\Python39\lib\site-packages\ruchatbot\bot\text_utils.py", line 155, in apply_word_function
    raise RuntimeError(msg)
RuntimeError: Could not choose a word among рад рада
```

**Comment by Koziev** [comment]
Вот это, конечно, странно. Что-то не срослось под Win.
В файле ../data/profile_rules_1.yaml есть строки типа:

```
    - 'Привет, буду $chooseAdjByGender(рад,рада) пообщаться'
```

При загрузке профиля тут происходит выбор одного из вариантов прилагательного согласно заданному в файле ```profile_1.json``` значению константы "gender". Все это происходит с помощью пакета ruword2tags. Подозреваю, что он как-то неправильно работает под Win в данном случае. Воспроизвести у себя не могу, не работаю под Win уже много лет :(
