### ISSUE TITLE
ошибка в релизе 0.0.0.2

### ISSUE THREAD

**Issue by timeshift92** [Koziev/chatbot#8]
Запускаю а он выдает ошибку:

> 2019-04-03 10:44:44,523 Loading Wordchar2VectorModel model files
2019-04-03 10:44:45,881 Loading wordchar2vector from ../tmp/wordchar2vector.dat
2019-04-03 10:44:45,882 loading projection weights from ../tmp/wordchar2vector.dat
2019-04-03 10:44:45,883 {'kw': {}, 'mode': 'rb', 'uri': u'../tmp/wordchar2vector.dat'}
Traceback (most recent call last):
  File "../PyModels/console_chatbot.py", line 46, in <module>
    machine.load_models(models_folder, w2v_folder)
  File "/chatbot/PyModels/bot/simple_answering_machine.py", line 117, in load_models
    self.word_embeddings.load_wc2v_model(self.wordchar2vector_path)
  File "/chatbot/PyModels/bot/word_embeddings.py", line 35, in load_wc2v_model
    self.wc2v = gensim.models.KeyedVectors.load_word2vec_format(wc2v_path, binary=False)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 1476, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/utils_any2vec.py", line 344, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/utils_any2vec.py", line 344, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: 'version'

**Comment by timeshift92** [comment]
еще хотелось узнать, может сможете подсказать что нужно для того чтобы быстрее запускать а то загрузка достаточно долго

**Comment by Koziev** [comment]
> ValueError: invalid literal for int() with base 10: 'version'
Подозреваю, это из-за не последней версии gensim. Запускаете не в докере, так? 
У меня pip show gensim выдает:

```
Name: gensim
Version: 3.6.0
Summary: Python framework for fast Vector Space Modelling
Home-page: http://radimrehurek.com/gensim
Author: Radim Rehurek
Author-email: me@radimrehurek.com
License: LGPLv2.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: scipy, numpy, smart-open, six
```

> еще хотелось узнать, может сможете подсказать что нужно для того чтобы быстрее запускать а то загрузка достаточно долго

Там один словарь очень большой грузится. Его надо сильно сокращать, потому что в нем всякая экзотическая лексика, не нужная для обычного чатбота. Но чтобы сократь, надо перерабатывать код той библиотеки, короче пока качество самого чатбота не выйдет на нужный уровень, не хочу отвлекаться.
